### PR TITLE
Fixed foreground and background color contrast ratio

### LINKED ISSUE #27: Background and foreground colors do not have a sufficient contrast ratio.
Low-contrast text is difficult or impossible for many users to read. [Learn more](https://dequeuniversity.com/rules/axe/2.2/color-contrast?application=lighthouse)

Failing elements on project page:
```
<a href="https://docs.google.com/forms/d/e/1FAIpQLSfFXvaTB9BXx7AEAmght09VcFW1Zq-lqeaKHRzjPjiczzAlrQ/viewform">in this form</a>
```

```
<span class="text-muted mt-2 small fixme-footer-moz-text">Mozilla is a global non-profit dedicated to putting you in control of your online experience and shaping the future of the web for the public good. Visit us at mozilla.org</span>

```

Failing elements on main page:
```
<h6 class="home-about-you-title mb-2">TELL US A BIT ABOUT YOURSELF</h6>
```

```
<div class="css-1492t68">type in your favorite languages</div>
```

```
<span>our latest tweets</span>
```

```
<div class="home-twitter-tweet">Latest issue to fix for project Bootstrap! HELP! https://fixmeparser.com/issues#1825 </div>
```

```
<span class="text-muted mt-2 small fixme-footer-moz-text">Mozilla is a global non-profit dedicated to putting you in control of your online experience and shaping the future of the web for the public good. Visit us at mozilla.org</span>
```

Failing elements for issues page:
```

<span class="mb-4 align-self-start">Tue Sep 18 2018</span>
```

```
<span class="text-capitalize ml-1">moderate</span>
```

```
<span class="text-capitalize ml-1">javascript</span>
```

```
<span class="text-capitalize ml-1">Issue</span>
```

```
<code>a</code>
```

```
<code>p</code>
```

```
<span class="mb-4 align-self-start">Tue Sep 18 2018</span>
```

```
<span class="text-capitalize ml-1">moderate</span>
```

```
<span class="text-capitalize ml-1">typescript</span>
```

```
<span class="text-capitalize ml-1">enhancement</span>
```

```
<span class="mb-4 align-self-start">Tue Sep 18 2018</span>
```

### PR DESCRIPTION
**Pull request by himankpathak**
### Description of the Change

Fixed the color contrast so there is sufficient contrast ratio between foreground and background.
Changed styles for text color where the test for "Color Contrast Analyzer" was failing.

### Benefits

Low-contrast text is difficult or impossible for many users to read. [Learn more](https://dequeuniversity.com/rules/axe/2.2/color-contrast?application=lighthouse)
Now the web app is more user-accessible to the users with good color contrast ratios.

### Verification Process

Verified that all the new colors pass all the tests on [Axe](https://dequeuniversity.com/rules/axe/2.2/color-contrast?application=lighthouse) rules by deque.
Verified all the changes on the required pages by deploying the web app on local server and testing the pages in different browsers.

**Home Page:**
home1

home2

**Issues Page:**
issues1

**Projects Page:**
projects1

### Applicable Issues

Closes #27

### CODE REVIEW

**Comment by alexdor** [comment]
looks good to me, just waiting for a verifications from @bacharakis before I'll merge this : )

**Comment by bacharakis** [comment]
Looks great @himankpathak ! Can also please change the color of the Twitter section in the main page to match the new color? That would be great!

**Comment by himankpathak** [comment]
Also changed the colors in the twitter section to match the new colors.
@bacharakis @alexdor review? :smile:

**Comment by himankpathak** [comment]
@alexdor actually the color assigned to the tag, do pass the test but the placeholder reduces its opacity to 50%
Should I change the opacity of the text to make it work?

**Comment by alexdor** [comment]
@himankpathak yeah feel free to change it : ) Just try to keep the text as opaque as possible (will passing the test)

**Comment by himankpathak** [comment]
@alexdor also I just checked the Date / Level of difficulty / Language / Type tag
They are passing the contrast test. Which tags are you talking about on the issues page?

**Comment by alexdor** [comment]
Links like this one : 
screenshot 2018-10-20 at 11 52 26

**Comment by himankpathak** [comment]
@alexdor requested changes made, please review :)

**Comment by alexdor** [comment]
There seems to be an issue with the placeholder of the input box. When clicking the input box, instead of the cursor going to the beginning it goes at the end of the placeholder

screenshot 2018-10-20 at 12 55 53

This might be resolve if you spread the base style, like here https://react-select.com/styles 

```
function styleFn(base, state) {
  // optionally spread base styles
  return { ...base, color: state.isFocused ? 'blue' : 'red' };
}
```

**Comment by himankpathak** [comment]
@alexdor done! passed the base styles to placeholder.
Idk how I missed such an important thing :sweat_smile:

**Comment by himankpathak** [comment]
@bacharakis reviews?

**Comment by bacharakis** [comment]
Thank you @himankpathak ! That looks good!

**Pull request merged**
