### PR TITLE
Fixed Redirection Bug

### PR DESCRIPTION
**Pull request by siddhant1**

### CODE REVIEW

**Comment by siddhant1** [comment]
If the previous one is not merged I will rebase and untrack those files

**Comment by alexdor** [comment]
Could you cherry-pick only your last commit so the diffing is easier?

**Comment by siddhant1** [comment]
Sure , Also I am having some issue where the firefox is blocking the popups on my click.
Is this expected?

**Comment by alexdor** [comment]
no this isn't expected, can you try the solution with appending the element to the Dom and clicking it through js to see if you have the same issue?

**Pull request closed without merging**
