### PR TITLE
Removed npm from docs since we use `yarn build-css`

### PR DESCRIPTION
**Pull request by siddhant1**

### CODE REVIEW

**Comment by siddhant1** [comment]
Previous Commits showing up because previous PR is not merged

**Comment by ashu8912** [comment]
Ahhh thanks siddhant somebody had to add it to the docs

**Comment by siddhant1** [comment]
Sure I will do it soon.

**Comment by siddhant1** [comment]
Looks Like I deleted this fork , sending in another one

**Pull request closed without merging**
