### PR TITLE
 Fixed Homescreen Image resolution

### PR DESCRIPTION
**Pull request by siddhant1**

### CODE REVIEW

**Comment by siddhant1** [comment]
fixes #123

**Comment by alexdor** [comment]
@siddhant1 I think smth went wrong with this pr, the files don't have any changes except new lines https://github.com/ossn/fixme/pull/127/files

**Comment by siddhant1** [comment]
Line 136 is the single line change that I have to do and sorry , my prettier did all the bad formatting

**Comment by siddhant1** [comment]
Do we have prettier setup to work on scss files on commit ?

**Comment by siddhant1** [comment]
If not , I think we should add that too

**Comment by siddhant1** [comment]
Openend #128 will have a look next

**Comment by alexdor** [comment]
Yeah prettier already works on scss files

**Pull request merged**
