### PR TITLE
added favicon512.

### PR DESCRIPTION
**Pull request by Deesteph55**
Closing issue #21

### CODE REVIEW

**Comment by alexdor** [comment]
Hi @Deesteph55, nice work : ) Could you also add the 192px icon? (you can do it either in this or to another pull request if you want)

**Comment by Deesteph55** [comment]
Hi Dorodoulis, I might not be able to do that on time because i closed out the git bash I was using and it might take me some time to re-familiarize myself with how this all works    On Thursday, September 27, 2018, 3:50:42 PM EDT, Alexandros Dorodoulis <notifications@github.com> wrote:  
 
 
Hi @Deesteph55, nice work : ) Could you also add the 192px icon? (you can do it either in this or to another pull request if you want)

**Comment by Muljayan** [comment]
Hi @Deesteph55  , 
I noticed that you have changed `<link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">` to `<link rel="shortcut icon" href="%PUBLIC_URL%/favicon512.png">` in the index.html file. 
Wouldn't it be better if the favicon.ico is left as it is in the index.html file ?

**Comment by alexdor** [comment]
Hi @Deesteph55 @Muljayan , the image from this pr looks really bad quality, does any of you want to try fixing the issue? 

Note: @Muljayan I agree with you, I don't think that the favicon should be updated

**Comment by Muljayan** [comment]
Hi @alexdor , I can fix this issue. @Deesteph55  are you OK with it?

**Comment by Muljayan** [comment]
Hi @alexdor i have resolved this issue as requested in #55 .

**Pull request closed without merging**
