### PR TITLE
Included About page

### LINKED ISSUE #29: Documentation: create the about page
Add information into the about page

- What does the platform does.
- Why do you need the platform
- How to use the platform

### PR DESCRIPTION
**Pull request by Muljayan**
closes #29 

### Created a skeleton and populated content for the about page. 
As the UI isn't available for the about page, created a skeleton and filled it with content provided in the comments section of issue #29.

### CODE REVIEW

**Comment by Muljayan** [comment]
### Images are from https://undraw.co/

**Comment by alexdor** [comment]
Looks good to me, waiting for verification from @bacharakis before I can merge it

**Comment by bacharakis** [comment]
@Muljayan I LOVE IT! Thank you so much, it's beautiful!

Quick question about the footer though, its height is intentionally that high?
[Check it out here](https://screenshots.firefox.com/dIOhxUhQpeqRgCU8/deploy-preview-66--reverent-brahmagupta-911c13.netlify.com)

**Comment by Muljayan** [comment]
@bacharakis your thoughts ?

**Comment by bacharakis** [comment]
Great work @Muljayan ! thank you so much!

**Pull request merged**
