### PR TITLE
Removed redundant Code and upgraded dependencies

### PR DESCRIPTION
**Pull request by siddhant1**

### CODE REVIEW

**Comment by alexdor** [comment]
Hi @siddhant1 thanks for the pr.

A few questions: 
Why is the service worker redundant ? 
Why is the test redundant?

Also this projects uses yarn, in order to update the dependencies you have to update yarn.lock as well

**Comment by siddhant1** [comment]
Can anyone check if this is a flakey test or I am missing something

**Comment by siddhant1** [comment]
The test file is just the default test and the serviceworker file also includes default code which according me the entire app is not using .

**Comment by alexdor** [comment]
The test is the default test but this doesn't mean that it isn't working. It checks if the app renders, it's basic and simple but not broken or redundant. 

The service worker is working on the production and is disabled on dev, are you experiencing something different?

**Comment by siddhant1** [comment]
Sure, the test file is checking for the rendering of the app , but only checks the mounting , let me add that again but I think we should write more tests.
For the serviceworker, sorry my bad I didn't checked it on the prod mode.
Should I make a final commit reverting the changes and upgrading the deps only?

**Comment by alexdor** [comment]
Yeah update the dependencies. Don't forget to use yarn to update the lock file as well. 

> There is `yarn upgrade-interactive --latest` to check outdated packages and select which ones you want to update

**Comment by siddhant1** [comment]
Also I think we should add yarn.lock

**Pull request closed without merging**
